trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: install
  jobs:
  - job: install
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
        displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies React app'

# - stage: build
#   dependsOn: install
#   jobs:
#   - job: Build
#     steps:
#     - task: NodeTool@0
#       inputs:
#         versionSpec: '18.x'
#         displayName: 'build Node.js'
#     - script: |
#         npm run build
#       displayName: 'Build React app'

- stage: deploy
  dependsOn: build
  jobs:
  - job: deploy
    steps:
    - task: AzureStaticWebApp@0
      displayName: 'Static Web App: '
      inputs:
        app_location: '/'
        api_location: ''
        output_location: 'build'
        azure_static_web_apps_api_token: $(token)
