trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: install
  jobs:
  - job: install
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
        displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies React app'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.SourcesDirectory)/build'
        artifactName: 'react-build'
        publishLocation: 'Container'
      displayName: 'Publish Build Artifacts'

- stage: deploy
  dependsOn: install
  jobs:
  - job: deploy
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'react-build'
        downloadPath: '$(Build.SourcesDirectory)/build'
      displayName: 'Download Build Artifacts'
    - task: AzureStaticWebApp@0
      displayName: 'Static Web App'
      inputs:
        app_location: '$(Build.SourcesDirectory)/build'
        api_location: ''
        output_location: ''
        azure_static_web_apps_api_token: $(token)
