trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: install
  jobs:
  - job: install
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
        displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies and build React app'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'build'
        artifact: 'react-build'
        publishLocation: 'pipeline'
      displayName: 'Publish Build Artifacts'

- stage: deploy
  dependsOn: install
  jobs:
  - job: deploy
    steps:
    - script: echo "Starting to download build artifacts"
      displayName: 'Echo Start Download'
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'react-build'
        paths: 'build'
      displayName: 'Download Build Artifacts'
    - script: ls -la build
      displayName: 'List Build Directory'
    - task: AzureStaticWebApp@0
      displayName: 'Deploy to Azure Static Web App'
      inputs:
        app_location: '/'
        api_location: ''
        output_location: 'build'
        repo_token: $(github_token)
        azure_static_web_apps_api_token: $(token)
