trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: npm install
  jobs:
  - job: install all packages
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        npm install
      displayName: 'Install dependencies React app'

- stage: npm build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        npm run build
      displayName: 'build React app'

- stage: deploy
  jobs:
  - job: deploy
    steps:
    - task: AzureStaticWebApp@0
      displayName: 'Static Web App: '
      inputs:
        app_location: '/'
        api_location: ''
        output_location: 'build'
        azure_static_web_apps_api_token: $(token)
