trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: install
  jobs:
  - job: install
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
        displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies React app'

- stage: deploy

  dependsOn: install
  jobs:
  - job: deploy
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'react-build'
        paths: 'build'
      displayName: 'Download Build Artifacts'
    - task: AzureStaticWebApp@0
      displayName: 'Static Web App: '
      inputs:
        app_location: '/'
        api_location: ''
        output_location: 'build'
    env:
      azure_static_web_apps_api_token: $(token)
      repo_token: $(github_token)
